//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchRunner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Qua\\Desktop\\Fanny_Heirdoo Suite\\Run")]
        public string SolutionBase {
            get {
                return ((string)(this["SolutionBase"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Qua\\Desktop\\Fanny_Heirdoo Suite\\Run")]
        public string KasperSolutionBase {
            get {
                return ((string)(this["KasperSolutionBase"]));
            }
            set {
                this["KasperSolutionBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Carsten\\Documents\\Visual Studio 2010\\Projects\\PlanetWarsBot - Athena\\Run" +
            "")]
        public string CarstenSolutionBase {
            get {
                return ((string)(this["CarstenSolutionBase"]));
            }
            set {
                this["CarstenSolutionBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Qua\\Documents\\Visual Studio 2010\\Projects\\PlanetWarsBot - Athena\\Run")]
        public string LaptopSolution {
            get {
                return ((string)(this["LaptopSolution"]));
            }
            set {
                this["LaptopSolution"] = value;
            }
        }
    }
}
